### ISSUE TITLE
Exclude dark theme styles

### ISSUE THREAD

**Issue by cgatian** [johannesjo/angular-material-css-vars#17]
Observation. A single Angular Material theme is roughly half the size as this package. 

| type | Size on Disk | Gzipped |
| :--- | --- | --- |
| Angular Material single theme |  62.9kb | 8.3 kB |
| angular-material-css-vars | 144 kB | 15.3 kB |

My guess is the dark and light both are getting built which doubles the size. Are both of these actually necessary?

**Comment by cgatian** [comment]
@johannesjo could you explain the need for light/dark being built in? Wouldn't you just want to generate the vars, and then swap CSS variables out at runtime with the appropriate values?

**Comment by johannesjo** [comment]
There is no "need" for it to be build in, but it is a core distinction for the angular material library and as this package is all about enabling custom user themes, it made sense to me, to include one as default. It should be pretty easy to deactivate during initialization though:
```
@mixin initMaterialCssVars(
  $dark-theme-selector: false,
) 
```
There is no super accessible mechanism yet to just use a dark theme though. I am open for suggestions how to handle this in a better manner.

**Comment by johannesjo** [comment]
I am closing this, but feel free to reopen this, if you were unable to come up with a solution.

**Comment by cgatian** [comment]
I think it's unavoidable. You need both light and dark palettes. We could
create a mixin that does only light or dark.

**Comment by literalpie** [comment]
I was able to get pretty far dynamically switching between dark and light mode by reassigning the variables inside a `.dark-theme` class block:
```
.dark-theme {
  --palette-background-background: $dark-background; 
  ...
}
```

This got me very far without doubling the bundle size. Pretty much everything worked as needed, but a few components had colors slightly off. It turned out, the problems are all in places where Material components use `is-dark` from the theme to pick different colors. There are over 10 different colors in around 5 different mixins that they use it for.

I think we could still make this approach work if we selectively call the 5ish component mixins that do special things based on the state of `is-dark`, and still use the approach above for background/foreground palettes.

I would have to try this out to see what the actual size savings are, or if it's worth the extra work. Do you have thoughts on whether this would work?

**Comment by johannesjo** [comment]
Not sure to be honest. In theory this should work pretty well without setting `--palette-background-background` as described above, if angular materials underlying color variable concepts would be used super strictly everywhere, but unfortunately they are not. They are conditional styles in addition to the color variables being applied. You can get an overview over those by search for `is-dark` inside`node_modules/@angular/material/_theming.scss`.

**Comment by henke-d** [comment]
Is it possible to change the background color dynamically (in runtime) the same way it is for primary, accent etc. For example, I would like to have the ability to set a custom background for dark mode.

Borrowing this thread as I thought it was somehow related to the above.

Thanks for a great library!

**Comment by johannesjo** [comment]
@henke-d please don't borrow threads. İt gets messy...

**Comment by johannesjo** [comment]
Not sure if this is helpful, but what we could do is making both light and dark optional like so:
```
  @at-root {
    @if $light-theme-selector {
      @include angular-material-theme($theme);
     }

    @if $dark-theme-selector {
      $mat-css-theme: $dark-theme !global;
      #{$dark-theme-selector} {
        @include angular-material-theme($dark-theme);
      }
    }
  }
```
This would give you the option to half the size in case you only need one of the two. This should already work if only using the light theme but not for when you only want to use the dark theme.
