### ISSUE TITLE
Provide migration instructions

### ISSUE THREAD

**Issue by dkimmich-onventis** [johannesjo/angular-material-css-vars#53]
Currently this library does not provide a changelog (as far as I can see). This makes it hard to find out if there are breaking changes.
For example, I don't know if I need to change anything with the update from version 0.3.9 to 1.1.0.

It would be great if you could add a changelog to clarify this.

You could use this format: https://keepachangelog.com/en/1.0.0/

**Comment by johannesjo** [comment]
I am trying to stick to semver. So a major version change is likely to break something/require you to adjust your code.

**Comment by dsimon-onventis** [comment]
Imho this is not enough. Based on the changes list in the link you provided, I have no idea what I need to adjust in my code.

What I am missing is a clear migration instruction, e.g.

> When migrating to version 1, you need to update your project to Angular 10

or something like this. This can be solved by introducing a changelog, adding a "Migration" section in the README would also work.

**Comment by johannesjo** [comment]
If complicated migrations need to happen, I'll write this in the readme. So far that hasn't been the case. 

I am also open to adding a more sophisticated solution if somebody wants to do it.

**Comment by Akkora** [comment]
I was looking for a changelog because I wanted to do the version 3 update, but couldn't find the breaking changes. Having one standardized place like a changelog would help here.

There are also ways to have an auto generated changelog based on commits. Maybe thats a solution here?
https://github.com/github-changelog-generator/github-changelog-generator
https://github.com/cookpete/auto-changelog

**Comment by json-derulo** [comment]
From now on, GitHub releases will be created which contain information about the changes, especially the breaking changes.
